name: _build-site

on: 
  workflow_call:
    outputs:
      version:
        description: 'Get current version'
        value: ${{ jobs.build.outputs.version }}

env:
  NODE_VERION: 18.x

jobs:
  get-info:
    uses: ./.github/workflows/_get-info.yml

  build:
    runs-on: ubuntu-latest
    needs: get-info
    outputs:
      version: ${{ needs.get-info.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.ref }}

      - name: Use Node.js ${{ env.NODE_VERION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERION }}
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: |
          npm run build:all
          npm run predeploy-gh-pages

      - name: Cache
        id: cache-site
        uses: actions/cache@v3
        with:
          path: ./docs
          key: docs-${{ needs.get-info.outputs.version }}-${{ github.run_id }}
